In [1]:
import cv2
import numpy as np
import glob
import matplotlib.pyplot as plt
import traceback
import os
from math import atan2, asin, degrees

In [2]:
CAMERA = 'oakd'
CALIBRATION_PATH = './calibration'
PATH = './find_pose'
CAMERA_CALIBRATION = f'{CALIBRATION_PATH}/{CAMERA}/calib_data_oakd.npz'

In [3]:
data = np.load(CAMERA_CALIBRATION)
camera_matrix = data['camera_matrix']
dist_coeffs = data['dist_coeffs']

print(camera_matrix)

[[3.14212361e+03 0.00000000e+00 1.92260024e+03]
 [0.00000000e+00 3.14649877e+03 1.08610836e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


In [4]:
for image_path in glob.glob(f'{PATH}/{CAMERA}/*'):
    print(image_path)
    frame = cv2.imread(image_path)

    processed = cv2.undistort(frame.copy(), camera_matrix, dist_coeffs)
    filename = f'./undistorted/{CAMERA}/undistorted_{os.path.basename(image_path)}'
    print(filename)
    print (cv2.imwrite(filename, cv2.undistort(frame, camera_matrix, dist_coeffs)))
    

./find_pose/oakd/capture_1756299630.png
./undistorted/oakd/undistorted_capture_1756299630.png
True
./find_pose/oakd/capture_1756299611.png
./undistorted/oakd/undistorted_capture_1756299611.png
True
./find_pose/oakd/capture_1756300966.png
./undistorted/oakd/undistorted_capture_1756300966.png
True
